### ISSUE TITLE
Initial Authorization does not work if Client Id / Client Secret are needed

### ISSUE THREAD

**Issue by eknoes** [mimicmobile/okhttp-oauth2-client#1]
For my OAuth2 Endpoint, I have to send Client ID / Client Secret as Authorization to Login with User / Password Combination.

`new OAuth2Client.Builder(user, pass, "id "secret", "url").grantType("password")`

Unfortunately I get a HTTP 401 Response, because `Utils.getAuthenticator()`at first tries to use 

`Credentials.basic(oAuth2Client.getUsername(),
oAuth2Client.getPassword());`

Although there is a second try with the correct credentials it does not work! That is due to the fact, that you use `.addHeader(Constants.HEADER_AUTHORIZATION, credential)` for the second try, which does *not* overwrite the first Authorization Header, but adds a second.

Replacing `addHeader` with `header` solved my problem, I will do a PR soon!

**Comment by corcoran** [comment]
Good catch, thanks for this!
