### ISSUE TITLE
errorMsg=invalid_client

### ISSUE THREAD

**Issue by ProgrammerXZ** [mimicmobile/okhttp-oauth2-client#11]
Map<String, String> map = new HashMap<>();
                map.put("grant_type", "client_credentials");
                map.put("scope", "basic");
                OAuth2Client client = new OAuth2Client.Builder(Common.clientID, Common.clientSecret, Common.tokenURL)
                                                     .parameters(map).build();

                client.requestAccessToken(new OAuthResponseCallback() {
                    @Override
                    public void onResponse(OAuthResponse response) {
                        if (response.isSuccessful()) {
                            String accessToken = response.getAccessToken();
                            LJLog.e("accessToken="+accessToken);
                        } else {
                            OAuthError error = response.getOAuthError();
                            String errorMsg = error.getError();
                            String errord = error.getErrorDescription();
                            LJLog.e("errorMsg="+errorMsg);
                            LJLog.e("errord="+errord);

                        }
                    }
                });

**Comment by corcoran** [comment]
This error isn't specific to this library. Please provide more details.
