### ISSUE TITLE
No Response, when i calling OAuth2Client

### ISSUE THREAD

**Issue by ahaneef29** [mimicmobile/okhttp-oauth2-client#4]
This is my code below, i'm trying to call getPublicToken() method, i don't see response.

My App crashed because of i'm calling in main thread.. then i implemented new Thread();.

please guide me, how to use this library.

    private void getPublicToken() {
         Toast.makeText(MainActivity.this, "getPublicToken Fired ", Toast.LENGTH_SHORT).show();

        new Thread(new Runnable() {
            @Override
            public void run() {
                OAuth2Client client = new OAuth2Client.Builder(ApiUtils.clientId, ApiUtils.clientSecret, ApiUtils.BASE_URL + "admin/api/apioauth2/token").build();
                OAuthResponse response = null;
                try {
                    response = client.requestAccessToken();
                    Toast.makeText(MainActivity.this, "response code >> " + response.getCode(), Toast.LENGTH_SHORT).show();
                    if (response.isSuccessful()) {
                        Toast.makeText(MainActivity.this, "response >> " + response.getBody(), Toast.LENGTH_SHORT).show();
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
    }

**Comment by corcoran** [comment]
The issue you're encountering is that Toast doesn't work on background threads.  You have a number of solutions to return the results to the UI thread from a background thread in Android.  Check out [this tutorial](http://www.vogella.com/tutorials/AndroidBackgroundProcessing/article.html) on some methods you can use.

If you want the library to handle threading for you, use the callbacks example [here](https://github.com/corcoran/okhttp-oauth2-client#callbacks).
