### ISSUE TITLE
Is there a reason for the android dependencies?

### ISSUE THREAD

**Issue by JustinTullgren** [mimicmobile/okhttp-oauth2-client#5]
Hi.

I was evaluating this project and I noticed it has a dependency on the app compat library.  Is this needed? 

It would be nice to be able to use this library in another JAR and that won't be possible with that dependency.

Thanks!

**Comment by corcoran** [comment]
I removed the unnecessary android support lib dependency in 2.4.0.  Hope that helps!

**Comment by JustinTullgren** [comment]
Thanks!
