### ISSUE TITLE
Why is this an AAR vs a Jar?

### ISSUE THREAD

**Issue by JustinTullgren** [mimicmobile/okhttp-oauth2-client#6]
Hi!

Thanks for the library.  It works well as an AAR.  I was just perusing the source though and I can't readily tell why it is an AAR over a straight jar.  Is there a reason behind it?  Is it possible you could release it as a jar vs aar?

I only ask because I like the simplicity of the library but its possible that we would want to bundle it in a fat jar so we can control downstream dependencies and avoid having people add it as a dependency in their build.gradle.  Fat AARs are hard to do and a lot of the projects out there are dead or not very active while fat jars are easy.

Please let me know.

Thanks!

**Comment by corcoran** [comment]
I think it could definitely be migrated over to a plain java library.  Feel free to take a crack at it and open a PR.  If I find the time I may look into it myself but by all means have at 'er!
